import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import LenisScroll from "@/components/lenis";

const geistSans = Geist({
    variable: "--geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={geistSans.className}>
                    <LenisScroll />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
